INSERT INTO product (name, category, price) VALUES ('Chair', 'furniture', 49.99);
INSERT INTO product (name, category, price) VALUES ('Table', 'furniture', 129.99);
INSERT INTO product (name, category, price) VALUES ('Lamp', 'lighting', 29.99);
INSERT INTO product (name, category, price) VALUES ('Sofa', 'furniture', 499.99);
INSERT INTO product (name, category, price) VALUES ('Light Bulb', 'lighting', 9.99);
INSERT INTO product (name, category, price) VALUES ('Rug', 'decor', 89.99);
INSERT INTO product (name, category, price) VALUES ('Bookshelf', 'furniture', 149.99);
INSERT INTO product (name, category, price) VALUES ('Desk', 'furniture', 199.99);
INSERT INTO product (name, category, price) VALUES ('Floor Lamp', 'lighting', 79.99);
INSERT INTO product (name, category, price) VALUES ('Curtains', 'decor', 59.99);
INSERT INTO product (name, category, price) VALUES ('Wall Art', 'decor', 39.99);
INSERT INTO product (name, category, price) VALUES ('Throw Pillow', 'decor', 19.99);
INSERT INTO product (name, category, price) VALUES ('Bed Frame', 'furniture', 299.99);
INSERT INTO product (name, category, price) VALUES ('Mattress', 'furniture', 399.99);
INSERT INTO product (name, category, price) VALUES ('Nightstand', 'furniture', 89.99);
INSERT INTO product (name, category, price) VALUES ('Ceiling Fan', 'lighting', 129.99);
INSERT INTO product (name, category, price) VALUES ('Mirror', 'decor', 74.99);
INSERT INTO product (name, category, price) VALUES ('Vase', 'decor', 24.99);
INSERT INTO product (name, category, price) VALUES ('Coffee Table', 'furniture', 159.99);
INSERT INTO product (name, category, price) VALUES ('TV Stand', 'furniture', 179.99);
INSERT INTO product (name, category, price) VALUES ('Pendant Light', 'lighting', 99.99);
INSERT INTO product (name, category, price) VALUES ('Table Lamp', 'lighting', 49.99);
INSERT INTO product (name, category, price) VALUES ('Desk Lamp', 'lighting', 34.99);
INSERT INTO product (name, category, price) VALUES ('Clock', 'decor', 44.99);
INSERT INTO product (name, category, price) VALUES ('Blender', 'appliances', 69.99);
INSERT INTO product (name, category, price) VALUES ('Toaster', 'appliances', 39.99);
INSERT INTO product (name, category, price) VALUES ('Microwave', 'appliances', 119.99);
INSERT INTO product (name, category, price) VALUES ('Refrigerator', 'appliances', 899.99);
INSERT INTO product (name, category, price) VALUES ('Washing Machine', 'appliances', 699.99);
INSERT INTO product (name, category, price) VALUES ('Dryer', 'appliances', 649.99);
INSERT INTO product (name, category, price) VALUES ('Dishwasher', 'appliances', 499.99);
INSERT INTO product (name, category, price) VALUES ('Oven', 'appliances', 799.99);
INSERT INTO product (name, category, price) VALUES ('Cookware Set', 'kitchen', 129.99);
INSERT INTO product (name, category, price) VALUES ('Cutlery Set', 'kitchen', 59.99);
INSERT INTO product (name, category, price) VALUES ('Cushion', 'decor', 29.99);
INSERT INTO product (name, category, price) VALUES ('Storage Box', 'decor', 34.99);
INSERT INTO product (name, category, price) VALUES ('Patio Chair', 'outdoor', 89.99);
INSERT INTO product (name, category, price) VALUES ('Garden Table', 'outdoor', 149.99);
INSERT INTO product (name, category, price) VALUES ('Outdoor Lamp', 'outdoor', 59.99);
INSERT INTO product (name, category, price) VALUES ('Hammock', 'outdoor', 119.99);
INSERT INTO product (name, category, price) VALUES ('Grill', 'outdoor', 249.99);
INSERT INTO product (name, category, price) VALUES ('Lawn Mower', 'outdoor', 399.99);
INSERT INTO product (name, category, price) VALUES ('Bluetooth Speaker', 'electronics', 99.99);
INSERT INTO product (name, category, price) VALUES ('Smart TV', 'electronics', 1199.99);
INSERT INTO product (name, category, price) VALUES ('Laptop', 'electronics', 999.99);
INSERT INTO product (name, category, price) VALUES ('Headphones', 'electronics', 199.99);
INSERT INTO product (name, category, price) VALUES ('Smartphone', 'electronics', 799.99);
INSERT INTO product (name, category, price) VALUES ('Tablet', 'electronics', 499.99);
INSERT INTO product (name, category, price) VALUES ('Printer', 'electronics', 149.99);
INSERT INTO product (name, category, price) VALUES ('Camera', 'electronics', 599.99);
